import "./globals.css";
import type { Metadata } from "next";
import { CustomThemeProvider } from "./theme/ThemeContext";
import { AuthProvider } from "./context/AuthContext";
import MobileBlocker from "./components/MobileBlocker";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AuthProvider>
          <CustomThemeProvider>
            <MobileBlocker />
            {children}
          </CustomThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
