import "./globals.css";
import type { Metadata } from "next";
import { CustomThemeProvider } from "./theme/ThemeContext";
import { AuthProvider } from "./context/AuthContext";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CustomThemeProvider>{children}</CustomThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
